language: scala
sudo: required

before_install:
  - sudo apt -qq update
  - ./scripts/install-deps.sh

script:
  - make verilog
  - make test-all

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
      - rgoncalves@iobundle.com
      - jsousa@iobundle.com
    on_success: never
    on_failure: always
