language: scala
sudo: required

before_install:
  - sudo apt -qq update
  - travis_wait 60 ./scripts/install-deps.sh
  - export RISCV=$HOME/riscv-tools

script:
  - make verilog
  - make test-all

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
      - rgoncalves@iobundle.com
      - jsousa@iobundle.com
    on_success: never
    on_failure: always
