language: scala
sudo: required

before_install:
  - sudo apt -qq update
  - sudo apt install -y make git autoconf g++ flex bison
  - git clone http://git.veripool.org/git/verilator
  - cd verilator
  - git pull
  - git checkout verilator_3_904
  - autoconf
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - make verilog
  - make test-all

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
      - rgoncalves@iobundle.com
      - jsousa@iobundle.com
    on_success: never
    on_failure: always
