language: scala
sudo: required

before_install:
  - sudo apt -qq update
  - sudo apt install -y verilator

script:
  - make verilog
  - make test-all

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
    on_success: never
    on_failure: always
