sudo: required

install: sudo apt install verilator && make verilog && make test-all && make test-all-verilator

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
    on_success: never
    on_failure: always
